### ISSUE TITLE
当我使用netcode包的时候发生了下面的问题 这种问题该如何解决？

### ISSUE THREAD

**Issue by NangFang01** [readyplayerme/rpm-unity-sdk-netcode-support#2]
![image](https://github.com/readyplayerme/rpm-unity-sdk-netcode-support/assets/148296274/010e84a0-c449-44c5-83eb-5ce9a40beb26)

**Comment by srcnalt** [comment]
Hi @NangFang01, you update core and netcode packages to fix the issue. Now it supports multimesh transfer.
